[package]
name = "dev-board"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.87"
tokio = { version = "1.21.2", features = ["macros"] }
warp = "0.3.3"
mobc = "0.7.0"
serde = {version = "1.0", features = ["derive"] }
serde_derive = "1.0"
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }
mobc-postgres = { version = "0.7.0", features = ["with-chrono-0_4"] }
log4rs="1.2.0"
log = "0.4.17"
dotenv = "0.15.0"
