version: '3.3'

services:
  # www:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #    - "8000:8000"
  #   links:
  #     - postgres
  #   depends_on:
  #     - postgres
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

